feat(script) bash to python
molgenis/molgenis-ops-helm pull request #343
Opened 2020-09-03 14:35 UTC by christianhilbrands

#### Checklist
- [ ] Functionality works & meets specifications (tested on rancher)
- [ ] Templates reviewed
- [ ] Added values to questions
- [ ] Bumped the chart version
- [ ] Updated appVersion (if needed)

2020-09-16 14:30 UTC, jvanveen requested changes
Het enige dat echt nodig lijkt, is het aanpassen van je fork naam naar de molgenis repo. De rest zijn vragen en/of suggesties. Inhoudelijk ziet het er prima uit, voor zover ik het kan beoordelen.

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/templates/getTargets-cronjob.yaml
> +                    wget {{ .Values.secret.githubtoken }}@raw.githubusercontent.com/christianhilbrands/molgenis-ops-helm/fix/prom-script-info/charts/molgenis-prometheus/scripts/serverlistRequester.py
Moet dat script eerst via remote wget worden opgehaald? Waarschijnlijk moet dan iig molgenis zijn straks, ipv je eigen fork (christianhilbrands)?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +        #     print(attribute, value)
Comments verwijderen?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +# from ruamel.yaml import YAML
Comments verwijderen?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +# from ruamel.yaml.compat import StringIO
Comments verwijderen?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +# print(serverlist)
Comments verwijderen?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +        # yaml.dump(blackbox_exporter_urls, outputFile)
Comments verwijderen?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +        # yaml.dump(node_exporter_targets, outputFile)
Comments verwijderen?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +urlAddress = 'molgenis23.gcc.rug.nl'
Is het misschien handig om deze variabele uit een env variabele te plukken en tegelijk een default waarde mee te geven?

2020-09-16 14:30 UTC, jvanveen commented on charts/molgenis-prometheus/templates/getTargets-cronjob.yaml
> +            image: python:3.8-alpine3.12
Netjes!

2020-09-24 08:12 UTC, christianhilbrands commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +urlAddress = 'molgenis23.gcc.rug.nl'
in overleg niet nodig, verwacht niet dat serverlist snel veranderd.

2020-09-24 08:12 UTC, christianhilbrands commented on charts/molgenis-prometheus/templates/getTargets-cronjob.yaml
> +            image: python:3.8-alpine3.12
dank ;-)

2020-09-24 08:14 UTC, christianhilbrands commented on charts/molgenis-prometheus/templates/getTargets-cronjob.yaml
> +                    wget {{ .Values.secret.githubtoken }}@raw.githubusercontent.com/christianhilbrands/molgenis-ops-helm/fix/prom-script-info/charts/molgenis-prometheus/scripts/serverlistRequester.py
done

2020-09-24 08:14 UTC, christianhilbrands commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +        #     print(attribute, value)
done

2020-09-24 08:14 UTC, christianhilbrands commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +# from ruamel.yaml.compat import StringIO
done

2020-09-24 08:14 UTC, christianhilbrands commented on charts/molgenis-prometheus/scripts/serverlistRequester.py
> +# print(serverlist)
done

2020-09-28 07:59 UTC, jvanveen submitted a review, later dismissed
Qua code ziet het er clean uit. Ik heb het alleen niet inhoudelijk kunnen testen.

2020-09-28 11:55 UTC, erikschaberg approved these changes
LGTM

2020-09-28 11:56 UTC, merged