feat(molgenis): add commander sidecar
molgenis/molgenis-ops-helm pull request #420
Opened 2021-04-09 15:08 UTC by sidohaakma

#### Checklist
- [ ] Functionality works & meets specifications (tested on rancher)
- [ ] Templates reviewed
- [ ] Added values to questions
- [ ] Bumped the chart version
- [ ] Updated appVersion (if needed)

2021-04-09 15:10 UTC, sidohaakma commented
![](https://github.trello.services/images/mini-trello-icon.png) [Add OIDC config to helm chart](https://trello.com/c/W1f2hYPv/2-add-oidc-config-to-helm-chart)

2021-05-25 11:47 UTC, tommydeboer commented
add some documentation in the question

2021-05-26 10:33 UTC, fdlk requested changes
Very much looking forward to this feature!

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +  - variable: oidc.identification.endpoints.userinfo
copy paste error, should be jwks

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +  - variable: oidc.identification.endpoints.authorisation
Starting 8.7, the endpoints can be discovered if you provide the issuer URL, propose to only ask for that in the questions

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/templates/oidc-secret.yaml
> +{{ if .Values.oidc.enabled -}}
Nice to make it a secret!

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/values.yaml
> +      authorization: https://auth.molgenis.org/oauth2/authorize
I'd say specify only issuerURI, unless we really want backwards compatibility with 8.6

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/Chart.yaml
> +version: 1.14.0
1.15.0 now, @tommydeboer and I skipped the queue

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +    description: "Do you want to connect to and ID-provider or authentication service"
and -> an

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +    description: "Type openid connect ID"
Explain that it ends up in the callback URL, see OidcClient metadata

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +    description: "Type openid connect name"
Explain that it ends up as label of the login button, see OidcClient metadata

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +    description: "Type in the client id"
Explain that it is provided by the id provider

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +    description: "Type in the client secret"
Explain that it is provided by the ID provider

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/questions.yml
> +    description: "Give the commander script as it was a script"
Probably can be formulated a bit more crisply

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/values.yaml
> +    tag: latest
Provide a question for this one I think

2021-05-26 10:33 UTC, fdlk commented on charts/molgenis/templates/commander-job.yaml
> +          args: ["-c", "fabric8-dependency-wait-service-linux-amd64 http://$(MOLGENIS_HOST):8080"]
this one comes up quite early, while bootstrapping is still in place, I think. In the startup prompt we use the `/api/v2/version` endpoint instead

2021-05-26 18:04 UTC, sidohaakma commented on charts/molgenis/values.yaml
> +    tag: latest
For the version you mean? Or both? The repo and the version?

2021-05-26 18:04 UTC, sidohaakma commented on charts/molgenis/questions.yml
> +    description: "Give the commander script as it was a script"
Hahaha, yes...

2021-05-27 11:00 UTC, fdlk commented on charts/molgenis/values.yaml
> +    tag: latest
version I think

2021-05-27 11:00 UTC, fdlk commented on charts/molgenis/templates/commander-job.yaml
> +          args: ["-c", "fabric8-dependency-wait-service-linux-amd64 http://$(MOLGENIS_HOST):8080"]
Yes, so you wait until bootstrapping is over

2021-05-27 12:42 UTC, sidohaakma commented on charts/molgenis/questions.yml
> +  - variable: oidc.identification.endpoints.userinfo
Removed in favor of issuerUri

2021-05-27 12:42 UTC, sidohaakma commented on charts/molgenis/questions.yml
> +  - variable: oidc.identification.endpoints.authorisation
Removed in favor of issuerUri

2021-05-27 15:57 UTC, fdlk approved these changes

2021-05-27 15:58 UTC, merged