chore: setup catalogue etl job WIP
molgenis/molgenis-ops-helm pull request #456
Opened 2021-08-20 15:10 UTC by connoratrug

- includes chart struct

todo: setup secrets and cleanup further cleanup chart

#### Checklist
- [ ] Functionality works & meets specifications (tested on rancher)
- [ ] Templates reviewed
- [ ] Added values to questions
- [ ] Bumped the chart version
- [ ] Updated appVersion (if needed)

2021-08-23 12:36 UTC, sidohaakma requested changes

2021-08-23 12:41 UTC, connoratrug commented on charts/molgenis-catalogue-etl/templates/tests/test-connection.yaml
> +apiVersion: v1
i have no idea, the helm init created it for me, but going of your comment i guess it can be removed

2021-08-23 12:48 UTC, connoratrug commented on charts/molgenis-catalogue-etl/templates/service.yaml
> +apiVersion: v1
removed

2021-08-24 12:12 UTC, sidohaakma requested changes
Add questions.yml to be able to deploy it on Rancher easily. I will look into this tomorrow morning as well.

2021-08-24 12:12 UTC, sidohaakma commented on charts/molgenis-catalogue-etl/Chart.yaml
> +description: A Helm chart for Kubernetes
Maybe make this more descriptive?

2021-08-25 07:15 UTC, connoratrug commented on charts/molgenis-catalogue-etl/Chart.yaml
> +description: A Helm chart for Kubernetes
good point :) , i have replaced the place holder with a real chart description

2021-08-25 07:52 UTC, sidohaakma approved these changes

2021-08-25 07:53 UTC, merged