fix/seed option armadillo
molgenis/molgenis-ops-helm pull request #498
Opened 2022-01-21 18:17 UTC by sidohaakma

#### Checklist
- [ ] Functionality works & meets specifications (tested on rancher)
- [ ] Templates reviewed
- [ ] Added values to questions
- [ ] Bumped the chart version
- [ ] Updated appVersion (if needed)

2022-01-21 18:19 UTC, sidohaakma commented
![](https://github.trello.services/images/mini-trello-icon.png) [Fix seed option](https://trello.com/c/XDS9676G/64-fix-seed-option)

2022-02-02 10:35 UTC, tommydeboer requested changes

2022-02-02 10:35 UTC, tommydeboer commented on charts/jupyterhub/README.md
> +4. Specify the repository and version in
Specify the version in what? :)

2022-02-02 10:39 UTC, sidohaakma commented on charts/jupyterhub/README.md
> +4. Specify the repository and version in
These files are not in place here.

2022-02-02 10:41 UTC, tommydeboer approved these changes

2022-02-02 10:41 UTC, merged