- added resourceLimits to pods
molgenis/molgenis-ops-helm pull request #504
Opened 2022-03-17 08:52 UTC by christianhilbrands

#### Checklist
- [ ] Functionality works & meets specifications (tested on rancher)
- [ ] Templates reviewed
- [ ] Added values to questions
- [ ] Bumped the chart version
- [ ] Updated appVersion (if needed)

2022-03-17 11:41 UTC, sidohaakma requested changes

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        molgenis-it-jdk15: |
The whole pod can be deleted `molgenis-it-jdk15`

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>                args: ""
The whole pod can be deleted `molgenis-it-jdk15-gradle`

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        r-3.5.2: |
Remove the whole pod `r-3.5.2`

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        r-3.6.2: |
Remove the whole pod `r-3.6.2`

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        r-4.0.3: |
Remove the whole pod `r-4.0.3`

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        helm: |
Remove the whole pod 'helm'

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        ansible: |
Remove the whole pod 'ansible'

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>                command: cat
Remove whole pod `node`

2022-03-17 11:41 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        node-dubnium: |
Remove whole pod `node-dubnium`

2022-03-17 12:13 UTC, sidohaakma requested changes

2022-03-17 12:13 UTC, sidohaakma commented on charts/molgenis-jenkins/values.yaml
>        python: |
Remove whole pod `python`

2022-03-17 12:35 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
> +              resourceLimitMemory: "4Gi"
here: https://www.jenkins.io/doc/pipeline/steps/kubernetes/ under podTemplate -> containers i see only resourceLimit and resourceRequest? am i looking to the wrong section?

2022-03-17 12:42 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
>        r-4.0.3: |
done

2022-03-17 12:42 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
>        helm: |
done

2022-03-17 12:48 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
> +              resourceLimitMemory: "4Gi"
done

2022-03-17 12:48 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
>                command: cat
done

2022-03-17 12:48 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
>        node-dubnium: |
done

2022-03-17 12:48 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
>        python: |
done

2022-03-17 12:49 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
> +              resourceLimitMemory: "4Gi"
done

2022-03-17 12:49 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
> +              resourceLimitMemory: "4Gi"
done

2022-03-17 14:20 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
> +              resourceLimitMemory: "4Gi"
done

2022-03-17 14:20 UTC, christianhilbrands commented on charts/molgenis-jenkins/values.yaml
> +              resourceLimitMemory: "4Gi"
done

2022-04-13 08:59 UTC, christianhilbrands commented
the PR is closed because there were problems with the new version of jenkins with the plugins. in the job plugin was a function deprecated and stopped the whole deployment of jenkins. i have ported the necessary pod templates to https://github.com/molgenis/molgenis-ops-helm/pull/507. this need to be looked at at an later date

2022-04-13 08:59 UTC, closed without merging