Jupyterhub v2t3
molgenis/molgenis-ops-helm pull request #531
Opened 2022-11-09 13:52 UTC by DickPostma

#### Checklist
- [x ] Functionality works & meets specifications (tested on rancher)
- [ x] Templates reviewed
- [ x] Added values to questions
- [ x] Bumped the chart version
- [ x] Updated appVersion (if needed)

2022-11-10 14:46 UTC, christianhilbrands requested changes
RfC

2022-11-10 14:46 UTC, christianhilbrands commented on charts/jupyterhub/Chart.yaml
> +appVersion: 3.0.0
zou haast adviseren om versie op 1.6.0 te zetten

2022-11-10 14:46 UTC, christianhilbrands commented on charts/jupyterhub/questions.yml
> +      type: string
waarom heb je dit aangepast?

2022-11-10 14:46 UTC, christianhilbrands commented on charts/jupyterhub/values.yaml
> +    cert-manager.io/cluster-issuer: letsencrypt
Morris vind het niet erg dat er letsencrypt gebruikt wordt?

2022-11-10 14:46 UTC, christianhilbrands commented on charts/jupyterhub/values.yaml
> +  profileList:
de profileList is een dynamische lijst, ik weet niet of het verstandig is om deze profiles te includen?

2022-11-10 14:54 UTC, DickPostma commented on charts/jupyterhub/questions.yml
> +      type: string
Ik kreeg een error bij Enum .. default is string

2022-11-10 14:54 UTC, DickPostma commented on charts/jupyterhub/values.yaml
> +    cert-manager.io/cluster-issuer: letsencrypt
In dit geval testen we met letsencrypt... in een live situatie maken we gebruik van echte certificaten.

2022-11-11 08:20 UTC, christianhilbrands approved these changes
LGTM

2022-11-11 08:20 UTC, merged